name: jalali_date
description: Persian (Jalali) date for Dart (Web/ Flutter/ DartVM). it converts Gregorian date to Persian date.
version: 0.1.5
author: Yamin Tashakkori<Yamin.tashakkori@gmail.com>
homepage: https://github.com/YaminT/Dart-Persian-Date

dependencies:
  flutter:
    sdk: flutter
environment:
  sdk: ">=1.19.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
