name: jalali_date
description: Persian (Jalali) date
version: 0.1.1
author: Yamin Tashakkori
homepage: iYamin.ir

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
